services:
  bentopdf:
    container_name: bentopdf
    image: ghcr.io/alam00000/bentopdf-simple:latest
    security_opt:
      - no-new-privileges:true
    ports:
      - ${BENTOPDF_PORT:-8080}:8080
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s