services:
  dozzle:
    container_name: Dozzle
    image: amir20/dozzle:latest
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - ${DOZZLE_PORT:-8892}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOZZLE_DATA_DIR:-./dozzle}:/data:rw
    environment:
     TZ: ${TZ}
     PUID: ${PUID}
     PGID: ${PGID}
     DOZZLE_AUTH_PROVIDER: forward-proxy
     DOZZLE_AUTH_HEADER_USER: X-Forwarded-User
     DOZZLE_AUTH_HEADER_EMAIL: X-Forwarded-Email
     DOZZLE_AUTH_HEADER_NAME: X-Forwarded-Preferred-Username
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
