services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    network_mode: host
    mem_limit: 4g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    environment:
      # Common runtime identity
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-100}
      VERSION: public
      PLEX_CLAIM: claim-${PLEX_CLAIM}
    volumes:
      - ${PLEX_CONFIG}:/config:rw
      - ${PLEX_MOVIES}:/movies:rw
      - ${PLEX_MUSIC}:/music:ro
      - ${PLEX_TV}:/shows:rw
    devices:
    # Optional - only needed if you want to use hardware acceleration for video encoding/decoding
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:32400/web
    restart: on-failure:5
